export const iljuMap = {
  gapja: '갑자',
  eulchuk: '을축',
  byeongin: '병인',
  jeongmyo: '정묘',
  mujin: '무진',
  gisa: '기사',
  gyeongo: '경오',
  sinmi: '신미',
  imsin: '임신',
  gyeyu: '계유',

  gapsul: '갑술',
  eulhae: '을해',
  byeongja: '병자',
  jeongchuk: '정축',
  muin: '무인',
  gimyo: '기묘',
  gyeongjin: '경진',
  sinsa: '신사',
  imo: '임오',
  gyemi: '계미',

  gapsin: '갑신',
  eulyu: '을유',
  byeongsul: '병술',
  jeonghae: '정해',
  muja: '무자',
  gichuk: '기축',
  gyeongin: '경인',
  sinmyo: '신묘',
  imjin: '임진',
  gyesa: '계사',

  gapo: '갑오',
  eulmi: '을미',
  byeongsin: '병신',
  jeongyu: '정유',
  musul: '무술',
  gihae: '기해',

  gyeongja: '경자',
  sinchuk: '신축',
  imin: '임인',
  gyemyo: '계묘',
  gapjin: '갑진',
  eulsa: '을사',
  byeongo: '병오',
  jeongmi: '정미',
  musin: '무신',
  giyu: '기유',

  gyeongsul: '경술',
  sinhae: '신해',
  imja: '임자',
  gyechuk: '계축',
  gapin: '갑인',
  eulmyo: '을묘',
  byeongjin: '병진',
  jeongsa: '정사',
  muo: '무오',
  gimi: '기미',

  gyeongsin: '경신',
  sinyu: '신유',
  imsul: '임술',
  gyehae: '계해',
};
