import type { Metadata } from 'next';
import './globals.css';
import { yclover, gmarket } from './fonts';
import { SWRegister } from '@/components/SWRegister';
import clsx from 'clsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={clsx(yclover.className, gmarket.className)}>
        <SWRegister />
        {children}
      </body>
    </html>
  );
}
